### ISSUE TITLE
2 x skipped heading https://uclalibrary.github.io/research-tips/turn-questions-into-keywords/

### ISSUE THREAD

**Issue by chillmarvelite** [UCLALibrary/research-tips#149]
Change headings for "Give it a try" and "Need some more help?" to H2

For Hype content, WAVE alerts for small text. Recommendation is to increase text.

**Comment by woof84** [comment]
the headings are H2! The Hype content is still the same, so leaving this open for now.

**Comment by dmcwo** [comment]
Looks like all issues have been addressed.
