### ISSUE TITLE
Multiple errors for https://uclalibrary.github.io/research-tips/get-configured/

### ISSUE THREAD

**Issue by chillmarvelite** [UCLALibrary/research-tips#156]
5 Contrast Errors

2 X Skipped heading level

**Comment by dmcwo** [comment]
https://github.com/UCLALibrary/research-tips/commit/9d0e940884d289a7e23d221555acd5d64c369bf5 fixes color contrast.

**Comment by dmcwo** [comment]
https://github.com/UCLALibrary/research-tips/commit/b5a27031047a8edb3743dd30022a53c46aa8327e fixes other issues

**Comment by dmcwo** [comment]
"Link to PDF" is an issue we can't fix unless we don't link to PDFs.

**Comment by dmcwo** [comment]
https://github.com/UCLALibrary/research-tips/commit/ac4b93c96ba38ce56c63a63ff17fad5e4afff3a9 updates accessibility-info
