### ISSUE TITLE
Fix skipped level heading https://uclalibrary.github.io/research-tips/contacting-instructors/ 

### ISSUE THREAD

**Issue by rromerorr** [UCLALibrary/research-tips#182]
"Authors" in the About this Tutorial section

**Comment by dmcwo** [comment]
Should be fixed for all pages - https://github.com/UCLALibrary/research-tips/commit/74c30088f56d7d3e0ec824d5c08f23e57508bf51

**Comment by rromerorr** [comment]
Thanks!
