### ISSUE TITLE
Fix text contrast errors https://uclalibrary.github.io/research-tips/sandbox/favorite-teaching-and-learning-quotes/

### ISSUE THREAD

**Issue by woof84** [UCLALibrary/research-tips#188]

**Comment by dmcwo** [comment]
text contrast issues fixed by previous css fix to blockquote

**Comment by dmcwo** [comment]
ooops. ^ is not true. errors still there.

**Comment by dmcwo** [comment]
ok - this time actually fixed. also fixed heading issue on page - https://github.com/UCLALibrary/research-tips/commit/85757c33cf3297311c8c46a1a0d4ab40e3a4124a
