### ISSUE TITLE
1x skipped heading level https://uclalibrary.github.io/research-tips/sandbox/accessibility-transparency/

### ISSUE THREAD

**Issue by woof84** [UCLALibrary/research-tips#206]

**Comment by dmcwo** [comment]
Fixed headings - https://github.com/UCLALibrary/research-tips/commit/06e74832242c06d7d3ea59f7b72ab79d1cf39ce2

2nd issue found related to tables.

**Comment by woof84** [comment]
fixed heading - ending tag was still h5!

**Comment by woof84** [comment]
added metadata!
