### ISSUE TITLE
Fix skipped heading level on https://uclalibrary.github.io/research-tips/find-the-guides/

### ISSUE THREAD

**Issue by rromerorr** [UCLALibrary/research-tips#208]
Missed first level heading on https://uclalibrary.github.io/research-tips/embeds/find-the-guides/#/. (The original link is incorrect - it leads to the tutorial and not the embed.)

**Comment by dmcwo** [comment]
https://github.com/UCLALibrary/research-tips/commit/b827e049d657500d426d100705a2b4839218fdd7
