### ISSUE TITLE
30x redundant link (alert) https://uclalibrary.github.io/research-tips/about/creative-team/

### ISSUE THREAD

**Issue by woof84** [UCLALibrary/research-tips#217]

**Comment by dmcwo** [comment]
Yikes! Which page is this one on?

**Comment by woof84** [comment]
Oops it's on this page!

https://uclalibrary.github.io/research-tips/about/creative-team/

**Comment by dmcwo** [comment]
https://github.com/UCLALibrary/research-tips/commit/b07bc4fc1ce3bfa9004043de185e6af1fdf00214
