### ISSUE TITLE
1x long alternative text https://uclalibrary.github.io/research-tips/about/

### ISSUE THREAD

**Issue by woof84** [UCLALibrary/research-tips#221]

**Comment by dmcwo** [comment]
I like the alt text for this image. But it is getting flagged as too long. Investigating options:
* https://www.d.umn.edu/itss/training/online/images/long_how/
* https://www.w3.org/WAI/tutorials/images/complex/
^ good resources - especially the 2nd one!

For now, going to shorten by removing the overlay text.

**Comment by dmcwo** [comment]
https://github.com/UCLALibrary/research-tips/commit/5cce5895dd1105e27d0eb62bd16fd9922cfc6a97
