### ISSUE TITLE
Fix heading structure on https://github.com/UCLALibrary/research-tips/issues/227

### ISSUE THREAD

**Issue by rromerorr** [UCLALibrary/research-tips#228]
There is no heading structure. Not sure how a screen reader would read this.

**Comment by dmcwo** [comment]
Is this one related to https://uclalibrary.github.io/research-tips/embeds/contacting-instructors/ -- -if so, the headings issue might have been fixed? Not coming up for me on a wave of the page.

**Comment by woof84** [comment]
Oops yes! Looks like it's fixed!
