### ISSUE TITLE
Fix headings on https://uclalibrary.github.io/research-tips/embeds/literature-reviews/#/

### ISSUE THREAD

**Issue by rromerorr** [UCLALibrary/research-tips#236]
All of the pages in the forward navigation indicate missed headings, or suggested headings

**Comment by dmcwo** [comment]
https://github.com/UCLALibrary/research-tips/commit/a81f18108f3083e056c14c4ad77ad5d88e9f0583
replaced w/ H5P version to improve accessibility and ability to update
