### ISSUE TITLE
Fix unordered bulleted list on https://uclalibrary.github.io/research-tips/embeds/literature-reviews/#/4/1

### ISSUE THREAD

**Issue by rromerorr** [UCLALibrary/research-tips#237]
On the "Skimming for What You Need" page

**Comment by dmcwo** [comment]
Couldn't find the issue with the unordered list. What was the error or alert?

**Comment by dmcwo** [comment]
https://github.com/UCLALibrary/research-tips/commit/a81f18108f3083e056c14c4ad77ad5d88e9f0583
replaced w/ H5P version to improve accessibility and ability to update
